name: chatbot-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - pip
  - pip:
    - fastapi
    - uvicorn
    - langchain
    - langchain-openai
    - openai
    - python-dotenv
    - langchain-community